### ISSUE TITLE
SI convention is for a (non-breaking) space between the quantity and the symbol

### ISSUE THREAD

**Issue by rob-smallshire** [cfobel/si-prefix#2]
See item #15 in this checklist:

http://physics.nist.gov/cuu/Units/checklist.html

"There is a space between the numerical value and unit symbol, even when the value is used in an adjectival sense, except in the case of superscript units for plane angle."

This library renders no such space.

**Comment by cfobel** [comment]
Thanks @rob-smallshire for pointing this out.
